### ISSUE TITLE
FYI: Transform issue with rendering models with multiple skinned mesh?

### ISSUE THREAD

**Issue by shrekshao** [pissang/qtek-model-viewer#1]
![image](https://user-images.githubusercontent.com/5031596/31835755-ab8f6eee-b587-11e7-9ba7-bb4face7a122.png)

The transform of the head and the glasses doesn't seem correct.

Model Link: https://github.com/shrekshao/glAvatar/blob/master/demo/models/patrick_no_shirt/patrick-no-shirt.gltf

**Comment by pissang** [comment]
Thanks shrek. Skinned mesh seems have a lot of problem currently

**Comment by pissang** [comment]
@shrekshao Fixed. I should use identity world matrix for skinned mesh. Which I did in the converter instead of loader previously. Also fixed the vertices stretch problem in saber model :)

**Comment by shrekshao** [comment]
Great! Thanks!
