### ISSUE TITLE
Binary glTF

### ISSUE THREAD

**Issue by nickkraakman** [pissang/qtek-model-viewer#10]
Very impressive work, @pissang ! Would love to have the option to convert to binary glTF as well. Is this something you will add soon?

**Comment by pissang** [comment]
Thanks! @nickkraakman . Currently binary glTF export is in the viewer http://pissang.github.io/qtek-model-viewer/editor and native app. Will also add it to the converter later:)

**Comment by nickkraakman** [comment]
@pissang that is very good news, since we really wish to integrate glTF into our augmented reality workflow! And what about compression using [WEB3D_quantized_attributes](https://cesium.com/blog/2016/08/08/cesium-web3d-quantized-attributes/)?

**Comment by pissang** [comment]
`WEB3D_quantized_attributes` is already supported in the converter, with `-q --quantize` argument.

**Comment by nickkraakman** [comment]
You are an absolute hero! Thanks so much for your great work.

**Comment by nickkraakman** [comment]
Hi @pissang, I have created a microservice for our AR platform using your fbx2gltf converter, and it works amazingly well! We will import the converted models into the Unity game engine in runtime, which is finally possible thanks to glTF. 

However, importing the models is a lot easier if we have the models in GLB format. Do you have a rough idea on when you plan to implement the GLB conversion option? We would be eternally grateful :-)

**Comment by pissang** [comment]
Hi @nickkraakman. Glad to hear it works well for your project!  I spend all time on another project these weekdays. Will start developing GLB export from this weekends. 

BTW is it needed for your project to embed the images in the GLB file?

**Comment by nickkraakman** [comment]
Hi @pissang, that timeline would be perfect! Really appreciate all your effort.

For our use case, the GLB would have to include the images as well, yes, since we want to import this one GLB file and have all the assets of the model inside of it. This way we have to make just one call to our server instead of multiple calls.

Please let me know if you need more info!

**Comment by pissang** [comment]
Hi @nickkraakman , I just add GLB export in the latest fbx2gltf script https://github.com/pissang/qtek/blob/master/tools/fbx2gltf.py. `-b --binary` is the argument.

**Comment by nickkraakman** [comment]
Hi @pissang, you rock! Thank you so much for this fast implementation.
