### ISSUE TITLE
The texture of BoxTextured.gltf is not displayed

### ISSUE THREAD

**Issue by cx20** [pissang/qtek-model-viewer#2]
I tried to display [Khronos glTF Samples](https://github.com/KhronosGroup/glTF-Sample-Models) with QTEK Model Viewer.
https://github.com/cx20/gltf-test

However, BoxTextured.gltf does not seem to be displayed correctly.
[QMV + BoxTextured.gltf result](https://cx20.github.io/gltf-test/examples/qtek/index.html?model=BoxTextured&scale=1)
![image](https://user-images.githubusercontent.com/1833979/32559307-31f2459e-c4ea-11e7-9b2b-d5f4b15efd20.png)

It is desirable to have the following results.
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BoxTextured
![image](https://github.com/KhronosGroup/glTF-Sample-Models/raw/master/2.0/BoxTextured/screenshot/screenshot.png)

I'm sorry if it seems that the usage of the library is incorrect.

**Comment by pissang** [comment]
@cx20 Thanks for the report. It seems the texture is NPOT and can't be repeated. Will fix that later.

**Comment by cx20** [comment]
@pissang I built the latest version of QMV.js and confirmed that it was fixed.
![image](https://user-images.githubusercontent.com/1833979/32607432-5d19aaac-c59c-11e7-9148-ef7bf1c0fa91.png)
