### ISSUE TITLE
The spine of Cesium Man seems is bent

### ISSUE THREAD

**Issue by cx20** [pissang/qtek-model-viewer#5]
It may be due to mind, but the Cesium Man's spine looks bent.

[QMV.js + CesiumMan.gltf result:](https://cx20.github.io/gltf-test/examples/qtek/index.html?model=CesiumMan&scale=1)
![image](https://user-images.githubusercontent.com/1833979/32615497-554c9778-c5b3-11e7-98ca-5082e65ad8d2.png)

[Three.js + CesiumMan.gltf result:](https://cx20.github.io/gltf-test/examples/threejs/index.html?model=CesiumMan&scale=1)
![image](https://user-images.githubusercontent.com/1833979/32615630-910ad90a-c5b3-11e7-819c-aff3ef67e7a5.png)

**Comment by pissang** [comment]
The skinning is wrong due to the weights sum in Cesium Man are not 1. Already fixed in https://github.com/pissang/qtek/commit/8dd12612c3cf4ebc99967c174893c4b160066b3a

**Comment by cx20** [comment]
@pissang  I confirmed that it has been fixed. Thanks :)

![image](https://user-images.githubusercontent.com/1833979/32660021-865ddbc2-c664-11e7-8ea8-fca80fed16de.png)
