### ISSUE TITLE
Is glTF Embedded format not supported yet?

### ISSUE THREAD

**Issue by cx20** [pissang/qtek-model-viewer#8]
I added the following format list to gltf-test.

https://github.com/cx20/gltf-test
![image](https://user-images.githubusercontent.com/1833979/32698873-60c4bd0e-c7ef-11e7-938a-9d2012e624a3.png)

I noticed that QMV.js supported the glTF-Binary format.
However, glTF-Embedded format seems to be unsupported.
When it is supported, the check will be green.

**Comment by pissang** [comment]
The loader can handle embedded base64 URI now:)

**Comment by cx20** [comment]
@pissang Thank you for your response. However, the build of the latest version did not go well. Build can be done, but LRUCache is undefined. 
See: https://github.com/pissang/qtek-model-viewer/issues/9

**Comment by cx20** [comment]
The format list of gltf-test has been updated. I confirmed that QMV.js became all green.
https://github.com/cx20/gltf-test
![image](https://user-images.githubusercontent.com/1833979/32728809-17ecc6a4-c8c5-11e7-8e77-881bd4c86ff5.png)

**Comment by pissang** [comment]
Thanks!
